version: '3'

services:
  webapi:
    build:     
      context: src/
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
      - "ConnectionStrings:BoilerplateDb=Host=postgres;Port=5432;Username=postgres;Password=password;Database=Boilerplate"
    ports:
      - '8000:80'
    depends_on:      
      - postgres
      
  postgres:
    image: postgres:15.1-alpine    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"    

volumes:
  postgres-volume:  
